server:
  port: 8080
spring:
  application:
    name: service
  datasource:
    pipe_hggl:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/pipe_hggl?characterEncoding=utf-8&useSSL=false&&useInformationSchema=true
      username: root
      password: 12345678
    pipe_platform:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/pipe_platform?characterEncoding=utf-8&useSSL=false&&useInformationSchema=true
      username: root
      password: 12345678

  thymeleaf:
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/webTemplate/
    suffix: .html
    servlet:
      content-type: text/html

zuul:
  cors:
    allowed-origins: '*'
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS

template:
  author: 李德水
  version: v1.0
  package: com.sgitg.hggl
  parent: DataServiceTemplateJavaParse


